### ISSUE TITLE
Build fails (with deprecated webpack functions)

### ISSUE THREAD

**Issue by phempel** [ssciwr/easydb-custom-data-type-ubhdgnd#5]
Hello, we wanted to test this plugin for compatibility with fylr. 

But the build with `make all` fails:

```
webpack --config webpack.config.js build/webfrontend/custom-data-type-ubhdgnd.entry.js build/webfrontend/custom-data-type-ubhdgnd.js
[webpack-cli] Failed to load '/home/philipp/go/src/github.com/programmfabrik/plugins/easydb-custom-data-type-ubhdgnd/webpack.config.js' config
[webpack-cli] TypeError: UglifyJsPlugin is not a constructor
    at Object.<anonymous> (/home/philipp/go/src/github.com/programmfabrik/plugins/easydb-custom-data-type-ubhdgnd/webpack.config.js:21:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at WebpackCLI.tryRequireThenImport (/home/philipp/go/src/github.com/programmfabrik/plugins/easydb-custom-data-type-ubhdgnd/node_modules/webpack-cli/lib/webpack-cli.js:223:30)
    at loadConfigByPath (/home/philipp/go/src/github.com/programmfabrik/plugins/easydb-custom-data-type-ubhdgnd/node_modules/webpack-cli/lib/webpack-cli.js:1406:38)
    at /home/philipp/go/src/github.com/programmfabrik/plugins/easydb-custom-data-type-ubhdgnd/node_modules/webpack-cli/lib/webpack-cli.js:1460:88
make: *** [Makefile:61: build/webfrontend/custom-data-type-ubhdgnd.js] Error 2
```

Maybe the referenced `UglifyJsPlugin` is just old/deprecated? I found https://stackoverflow.com/questions/69468568/typeerror-webpack-optimize-uglifyjsplugin-is-not-a-constructor. 

Is there anything we need to fix here (use some specific versions?), or could you please update the referenced libraries in the plugins?

Best regards, 

Philipp Hempel

Programmfabrik GmbH

**Comment by nils-stefan-weiher** [comment]
Dear Philipp Hempel,

sorry the code is not up to date in this repository, I used this repository to cooperate with @iulusoy and @GwydionJon on the implementation of the CustomDataTypeUpdater.

The latest version is not hosted on Github, but on the Gitlab Instance of UB-Heidelberg.

https://gitlab.ub.uni-heidelberg.de/fdm/easydb-custom-data-type-ubhdgnd/

I can send a pull request to update the code here also.

Thanks for reaching out and testing.

Best Regards,

Nils Weiher

**Comment by phempel** [comment]
Thank you! 

For now, we will use the version from gitlab then.
